name: MonsieurBarbier
favicon: null
layout_spectrum: 0.22455181670375168
typography_spectrum: 0.42766254651360214
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6587225969415158
  lightness: 0.9449613108299673
  saturation: 0.18720655608922243
  rhythmicContrast: 0.874504632782191
purpose: []
